- src/reply.rs
`two_finger` and `edge` are separate variants (see [`man 5 sway-input`](https://github.com/swaywm/sway/blob/master/sway/sway-input.5.scd#L164)).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jaycefayne/swayipc-rs/1)
> Fix ScrollMethod variants

- src/event.rs
This makes associating handlers with event types easier for clients.
> Make EventType Copy, Eq, and Hash.

- Cargo.toml
- src/event.rs
- src/reply.rs
It seems that on newly created, empty workspaces the representation can be `null`, with this change the representation gets deserialized to an empty string in that case.
Another option would be to switch to Option<String>, which I haven't done here to preserve backwards compatibility.
Additionally this changes from requiring `serde_derive` directly towards using the `derive` feature of `serde`, because the compiler didn't like `use`ing a trait and macro of the same name.
> handle `null` for Workspace::representation

- src/socket.rs
This allows `swayipc-rs` to be used in programs that support both i3 and sway,
without having to add two separate dependencies such as `swayipc-rs` for sway
and `i3ipc-rs` for i3.
I plan on using this crate over i3ipc-rs in `i3status-rust` if this is merged. Have tested in both sway and i3.
> Allow fallback to I3SOCK for compat with i3

- src/socket.rs
Fixes https://github.com/greshake/i3status-rust/issues/705 and https://github.com/greshake/i3status-rust/pull/667#issuecomment-631238476
Note: I have not tested this myself but I don't believe there are any problems with the logic here.
> i3 compat: add fallback to --get-socket-path

- src/reply.rs
See https://github.com/swaywm/sway/commit/03ca8596d6bcec0a83567d9b51a71ccc7db197e5
To test, run the hovered_window example and start `xev`.
Before this PR it will crash: ```Error: Error("missing field `instance`", line: 1, column: 784)```
> fix: X11 window properties should be optional

- types/src/reply.rs
This project does not explicitly claim to keep compatibility with i3, but it probably can be made so without too much effort. It would especially be useful as i3ipc-rs is now inactive.
Here are the changes I could find to fix the problems when using my project under i3 (see https://github.com/lbonn/i3-focus-last/issues/3)
> Improve i3 compatibility

- types/src/reply.rs
Sway doesn't give disabled outputs ids, but the deserializer is expecting it,.
> Fix disabled outputs have no id

- types/src/reply.rs
Sway-ipc leaves out the `visible` key in the values `current` and `old` on `WorkspaceEvent`. I fixed that with making the `visible` key optional (maybe not the best fix).
> Fix Error on deserializing Event WorkspaceEvent

- types/src/reply.rs
sway-ipc(7) actually defines `binding` as an separate object, so no need
to flatten here.
> Example Event:
```json
{
"change": "run",
"binding": {
"command": "workspace 2",
"event_state_mask": [
"Mod4"
],
"input_code": 0,
"symbol": "2",
"input_type": "keyboard"
}
}
```
I verified, that I can now receive something like this: `Binding(BindingEvent { change: Run, binding: BindingEventOps { command: "focus up", event_state_mask: ["Mod4"], input_code: 0, symbol: "g", input_type: Keyboard } })` on Sway `1.5`.
Also I read
```
├─────────────────┼───────────┼─────────────────────────────┤
│     symbol      │  string   │ For keyboard bindsyms, this │
│                 │           │ is the bindsym for the      │
│                 │           │ binding. Otherwise, this    │
│                 │ …
```
> fix BindingEvent, that had always BindingEventOps: None

- types/src/reply.rs
On i3, the output of `swaymsg -t get_workspaces -r`
looks like this:
```
{
"id": 93873798666352,
"num": 1,
"name": "1:    ",
"visible": true,
"focused": true,
"rect": {
"x": 0,
"y": 18,
"width": 1920,
"height": 1062
},
"output": "eDP-1",
"urgent": false
}
```
Attempting to call `get_workspaces` from this crate would panic with one
of the following messages:
```
SerdeJson(Error("missing field `layout`", line: 1, column: 152))
SerdeJson(Error("missing field `orientation`", line: 1, column: 152))
```
To remain compatible with i3, let serde default initialize either of
these values as they won't be present on i3.
This incompatibility was observed through workstyle as reported here:
https://github.com/pierrechevalier83/workstyle/issues/21
This commit has been tested locally and gets …
> Fix panic when calling `get_workspace` on i3

- types/src/reply.rs
Node `id`s are i64, but some fields that reference these ids such as `focus` were still i32.
Should fix https://github.com/greshake/i3status-rust/issues/1588
> fix: node ids are i64

- types/src/reply.rs
This allows events to be passed around to multiple places (eg broadcasted) once received, rather than having to receive them multiple times.
It also fixes `WorkspaceEvent` returning a `Node` instead of a `Workspace`.
Awesome crate btw, cheers.
> Add `Clone` to all reply types, fix workspace event types

- types/src/utils/node.rs
This adds `Node::iter` that allows to iterate through all nodes breadth-first.
Please, let me know if you want me to make any changes to the code!
> Add Node::iter

- async/src/connection.rs
- async/src/socket.rs
- blocking/src/connection.rs
- blocking/src/socket.rs
- types/src/error/mod.rs
I maintain a project that uses swayipc to communicate to the window manager.
Recently, I added support for hyprland and I got [a report](https://github.com/pierrechevalier83/workstyle/issues/49) that my executable was crashing.
The crash was originating from [a call to `Connection::new()`](https://github.com/pierrechevalier83/workstyle/blob/b85006e6af8e45fc36d613ac92b51699646a4de8/src/window_manager.rs#L263), and the user confirmed that they didn't have Sway or I3 installed on their machine.
I had assumed that this call would err if it couldn't connect to the window manager (which it does as long as i3 or sway is installed), since it returned a `Result`, so I used it to decide which window manager to connect to: try sway or i3 first and if that fails, try hyprland.
Now I've read the code …
> fix: don't crash when connecting and neither i3 nor sway is installed

- types/src/reply.rs
```rust
// source file: types/src/reply.rs
pub struct Node {
/// ...
/// (Only xwayland views) An object containing the title, class, instance,
/// window_role, window_type, and transient_for for the view.
pub window_properties: Option<WindowProperties>,
/// ...
```
`WindowProperties` should have 6 fields: `title`, `class`, `instance`, `window_role`, `window_type`, and `transient_for`. However, in the definition of the struct `WindowProperties`, the field `window_type` is missing. This PR brings it back.
> fix: bring back missing field of WindowProperties

- types/src/utils/event.rs
- types/src/utils/mod.rs
Need it for registering events listeners dynamic, and is not possible to maintain this code downstream due to `non_exhaustive`.
> feat: add Event::event_type

- types/src/reply.rs
i3 has another possible scratchpad state that is missing in this repo's enum:
https://github.com/i3/i3/blob/4661e74b5ebe8727d1b0f8c29b1697f1f42daf70/include/data.h#L796
To be honest I am not entirely sure why it is important but I've managed to stumble on it when running i3 and it caused serialization errors.
> Add i3 "changed" scratchpad state

- async/src/common.rs
- blocking/src/common.rs
This reduces the number of system calls done for reading an incoming IPC message from 4 to 2 and improves latency
> optimize by merging 3 unbuffered reads on IPC message header into one

- types/src/reply.rs
get_inputs calls started failing on my machine because wlr_virtual_keyboard_v1 doesn't have vendor or product fields (`cargo test` fails as well). swaymsg treats these as optional in practice and uses 0 by default for the values.
> Make input vendor and product fields optional
